### ISSUE TITLE
Window Length Issue

### ISSUE THREAD

**Issue by clairedd** [clairedd/sks-project#2]
sks.py broke earlier when the length of the window was changed from 50 seconds to 6 seconds. Window length is defined in the code mainly in two places: in calculations for the funciton getsksstuff and when choosing which part of the SKS waveform ObsPy should window around. The issue seems to be coming from the former section. The code below is the beginning of the section where the code stops working. 

```
 for stW in st.slide(window_length=6., step=.1):
        dt += .1
        if debug:
           print('Rotating around all Phis')
       for phi in phis:
            # Rotate the data by the given phi
            comp1 = np.cos(phi)*stF[0].data - np.sin(phi)*stF[1].data
           comp2 = np.sin(phi)*stW[0].data + np.cos(phi)*stW[1].data
           # comp1 is our "fast" component and comp2 is slow
```

I have added a lot of debugging statements to the function, and set `debug=True` for the function. The debug statement in the code above (where it prints 'Rotating around all Phis') does not show up when the code is run. Yet the code does not produce an error for the for loop, instead giving the following error for a statement 40 lines down:

```
  Traceback (most recent call last):
      File "sks.py", line 220, in <module>
           fast, delay, stF, stW, comp1, comp2 = getsksstuff(st)
      File "sks.py", line 82, in getsksstuff
          phigood = np.rad2deg(phigood)
   **UnboundLocalError: local variable 'phigood' referenced before assignment**
```

The code just seems to be booting out of the `for` loop where all of the calculations are being made (including where phigood is defined, hence why we are getting the `UnboundLocalError`), and I can't seem to figure out why it would be doing this. Just putting this out here to see if anyone has ideas. I'll also put the broken version of the code in a forked directory so that everyone can see the changes that got made!

**Comment by clairedd** [comment]
This code is clunky and the math is wrong, so the same process has been re-written in `splittingcalc.py`. Please refer to that from now on.
